name: Build APK

on:
  push:
    branches: [ "main", "principal" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Instalar Expo CLI
        run: npm install -g expo-cli

      - name: Gerar pasta Android
        run: npx expo prebuild --platform android

      - name: Compilar APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - name: Enviar APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: android/app/build/outputs/apk/release/app-release.apk
